name: Cache APK file
description: Caches apk files to avoid build

runs:
  using: composite
  steps:
    - name: Cache new APK
      uses: actions/cache/save@v3
      with:
        path: ${{ env.ANDROID_APP_PATH }}
        key: |
          APK-${{ hashFiles(
            '/home/runner/work/react-native-client-sdk/react-native-client-sdk/example/**/*',
            '/home/runner/work/react-native-client-sdk/react-native-client-sdk/android/**/*/components/**/*',
            '/home/runner/work/react-native-client-sdk/react-native-client-sdk/src/**/*',
            '/home/runner/work/react-native-client-sdk/react-native-client-sdk/yarn.lock'
          ) }}
