name: Lint & Types
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.0
          cache: 'yarn'
      - name: Install node dependencies
        run: yarn
      - name: Build Types
        run: yarn build
      - name: Check types
        run: yarn tsc
      - name: Lint
        run: yarn lint:check
      - name: Prettier
        run: yarn format:check
